#!/usr/bin/env bash
# Transfer a file to a server
if [ $# -ge 3 ]
then
    if [ $# -eq 4 ]
    then
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":.
    else
	scp -o StrictHostKeyChecking=no "$1" "$3"@"$2":.
    fi
else
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
