#!/usr/bin/env bash
# Install NGINX server and set message in landing page
apt-get update -y
apt-get install nginx -y
echo "Holberton School" > /var/www/html/index.nginx-debian.html
service nginx start
