#!/usr/bin/env bash
# Install NGINX server and set message in landing page
sudo apt-get update -y
sudo apt-get install nginx -y
sudo echo 'Holberton School' > /var/www/html/index.nginx-debian.html
sudo systemctl restart nginx.service
service nginx start
