#!/usr/bin/env bash
#Install load balancer
sudo apt update
sudo apt-get install -y haproxy=1.6.\*
setup="
frontend firstbalance
	 bind *:80
	 mode http
	 default_backend webservers

backend webservers
	balance roundrobin
	server 1278-web-01 35.231.235.242:80 check
	server 1278-web-02 35.175.190.73:80 check
"
echo "$setup" >> /etc/haproxy/haproxy.cfg
echo "ENABLED=1" >> /etc/default/haproxy
