#!/usr/bin/env bash
# Set nginx user and listen in port 8080
sudo chmod u+rw /etc/nginx/nginx.conf
sudo sed -i "s/#user www-data;/user nginx;/" /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/" /etc/nginx/sites-available/default
sud - nginx -c "service nginx restart"
